# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_MAC <- function(X_bind, Y_bind, list_i, list_j, n) {
    .Call('_mBoost_compute_MAC', PACKAGE = 'mBoost', X_bind, Y_bind, list_i, list_j, n)
}

